image: gradle:4.5-alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - compile
  - test

before_script:
  #  - echo `pwd` # debug
  #  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

# npm install and compile gulpfile
compile:
  stage: compile
  image: opendigitaleducation/node
  script:
    - npm install
    - node_modules/gulp/bin/gulp.js build

# test node (javascript/typescript...)
test_node:
  stage: test
  image: opendigitaleducation/node
  script:
    - npm test

# test all java classes and build gradle
test_gradle:
  stage: test
  image: gradle:4.5-alpine
  script:
    - gradle test --no-build-cache --rerun-tasks
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle


after_script:
  - echo "End CI"