node:
  image: opendigitaleducation/node:10-alpine
  working_dir: /home/node/app
  volumes:
  - ./:/home/node/app
  - ~/.npm:/.npm
  - ~/.gitconfig:/home/node/.gitconfig
  - ~/.npmrc:/home/node/.npmrc
  - ~/.bowerrc:/home/node/.bowerrc
