ALTER TABLE notes.matiere DROP CONSTRAINT code_unique;
ALTER TABLE notes.matiere ADD CONSTRAINT libelle_court_unique UNIQUE(libelle_court);
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('999999','DOCUME','INFORMATION DOCUMENTATION');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('999998','CONSER','CONSERVATOIRE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('999996','CHAAP','ATELIER ARTISTIQUE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('999997','STAGE','STAGE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('030102','AL2ND','ALLEMAND LV2');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('030101','all1''','ALLEMAND LV1');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('030101','ALL1''','ALLEMAND LV1');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('030101','Allemand','ALLEMAND LV1');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('030201','ANG1','ANGLAIS LV1');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('030201','Anglais','ANGLAIS LV1');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('007400','DP3','DECOUVERTE PROFESSIONNELLE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('007400','DP3''','DECOUVERTE PROFESSIONNELLE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('007400','DP3''''','DECOUVERTE PROFESSIONNELLE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('043800','ECM','ENSEIGNEMENT MORALE ET CIVIQUE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('081300','ED-CH','EDUCATION MUSICALE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('100100','EPS''','EDUCATION PHYSIQUE ET SPORTIVE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('100100','EPS1','EDUCATION PHYSIQUE ET SPORTIVE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('100100','EPS2','EDUCATION PHYSIQUE ET SPORTIVE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('030602','ESP2''','ESPAGNOL LV2');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('020700','FRAN','Français');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('020700','Français','Français');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('043700','H-G-EMC','HISTOIRE-GEOGRAPHIE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('043700','HIGE''','HISTOIRE-GEOGRAPHIE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('020300','LCA','LANGUE ET CULTURE DE L''ANTIQUITE LATIN');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('020300','LcaLATIN','LANGUE ET CULTURE DE L''ANTIQUITE LATIN');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('020400','LGR','LANGUE ET CULTURE DE L''ANTIQUITE GREC');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('081300','musi','EDUCATION MUSICALE');
INSERT INTO notes.matiere(code, libelle_court, libelle_long) VALUES ('070800','Techno','TECHNOLOGIE');
