GRANT USAGE ON SCHEMA viesco TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA viesco TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA viesco TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA viesco TO "apps";

GRANT USAGE ON SCHEMA memento TO "apps";
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA memento TO "apps";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA memento TO "apps";
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA memento TO "apps";