INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('099800','AEART','ACCOMPAGN. EDUCATIF- PRATIQ.ART.CULTUREL');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('009800','AEAID','ACCOMPAGN.EDUCATIF- AIDE DEVOIRS LECONS');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('509800','AELVE','ACCOMPAGN.EDUCATIF- PRATIQUE ORALE LVE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('006600','ACCPE','ACCOMPAGNEMENT PERSONNALISE' );
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('109800','AESPO','ACCOMPAGNEMT EDUCATIF- PRATIQUE SPORTIVE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('008700','AIDIN','AIDE INDIVIDUALISEE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030B01','ALLS','ALLEMAND DE SECTION');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030109','ALL9','ALLEMAND LANGUE DE SECTION');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030101','ALL1','ALLEMAND LV1');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030102','ALL2','ALLEMAND LV2');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030B02','ALL2ND','ALLEMAND LV2 NON DEBUTANT');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030A01','AGLS','ANGLAIS DE SECTION');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030209','AGL9','ANGLAIS LANGUE DE SECTION');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030204','AGL4','ANGLAIS LV RENFORCE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030201','AGL1','ANGLAIS LV1');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030202','AGL2','ANGLAIS LV2');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030A02','AGL2ND','ANGLAIS LV2 NON DEBUTANT');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('278600','CIRQU','ARTS DU CIRQUE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('090100','A-PLA','ARTS PLASTIQUES');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('100700','ATHLE','ATHLETISME');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('106100','BADMI','BADMINTON');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('100900','BASKT','BASKET-BALL');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('174000','BATIM','BATIMENT');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('084300','CHKCO','CHANT CHORAL COLLECTIF');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030402','CHI2','CHINOIS LV2');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('082500','DANSE','DANSE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('000M00','DECM','DECOUVERTE DES METIERS');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('007400','DECPR','DECOUVERTE PROFESSIONNELLE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('104100','EPSCO','EDUC. PHYSIQUE ET SPORTIVE DE COMPLEMENT');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('081300','EDMUS','EDUCATION MUSICALE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('081000','EMUGT','EDUCATION MUSICALE GENERALE ET TECHNIQUE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('100100','EPS','EDUCATION PHYSIQUE ET SPORTIVE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('083400','N-ART','ENSEIGNEMENT ARTISTIQUE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('043800','EMC','ENSEIGNEMENT MORAL ET CIVIQUE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030604','ESP4','ESPAGNOL LV RENFORCE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030602','ESP2','ESPAGNOL LV2');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('101000','FOOTB','FOOTBALL');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('000800','F-GEN','FORMATION GENERALE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('001000','F-PRO','FORMATION PROFESSIONNELLE(SES)');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('084400','FVOCA ','FORMATION VOCALE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('020700','FRANC','FRANCAIS');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('023900','FRLSE','FRANCAIS LANGUE SECONDE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('175500','HABIT','HABITAT');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('101300','HANDB','HANDBALL');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('043700','HI-GE','HISTOIRE-GEOGRAPHIE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('313500','HYASE','HYGIENE ALIMENTATION SERVICES');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('030902','ITA2','ITALIEN LV2');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('101400','JUDO','JUDO');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('024000','LCALG','LANG. ET CULT. DE L''ANTIQ. LATIN ET GREC');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('000L00','LDSF','LANGUE DES SIGNES FRANCAISE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('038007','LVRNS','LANGUE VIVANTE REGIONALE NON SUIVIE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('020400','LCAGR','LANGUES ET CULTURES DE L''ANTIQUITE GREC');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('020300','LCALA','LANGUES ET CULTURES DE L''ANTIQUITE LATIN');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('061300','MATHS','MATHEMATIQUES');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('470200','MODAS','MODULE D''AIDES SPECIFIQUES');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('083200','MUSIQ','MUSIQUE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('101500','NATAT','NATATION ET ACTIV.SPORTIV. AQUATIQUES');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('470400','PAREX','PARCOURS D''EXCELLENCE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('062300','PH-CH','PHYSIQUE-CHIMIE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('031109','POR9','PORTUGAIS LANGUE DE SECTION');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('031101','POR1','PORTUGAIS LV1');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('031102','POR2','PORTUGAIS LV2');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('081100','PCVOI','PRATIQ. COLLECTIVE VOCALE  INSTRUMENTALE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('031401','RUS1','RUSSE LV1');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('060600','SCIEN','SCIENCES');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('062900','SVT','SCIENCES DE LA VIE ET DE LA TERRE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('073800','STECH','SCIENCES ET TECHNOLOGIE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('001400','SOUTN ','SOUTIEN');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('070800','TECHN','TECHNOLOGIE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('101800','TENIS','TENNIS');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('278500','THEAT','THEATRE');
INSERT INTO notes.matiere (code, libelle_court, libelle_long) VALUES ('102100','VOLEY','VOLLEY BALL');